### ISSUE TITLE
privacy/certificate issue

### ISSUE THREAD

**Issue by visualizor** [gtalarico/apidocs.samples#13]
domain no longer works. browser says connection not private.
![image](https://github.com/gtalarico/apidocs.samples/assets/25107288/6e813dd7-ad52-4f54-b955-beb0c59b42e1)

**Comment by gtalarico** [comment]
Thanks for the heads up can you try again?
@visualizor

**Comment by visualizor** [comment]
all good now. thanks for the fast action!
